---
title: "Introduction to R"
author: "CRC1678 INF"
format: 
  revealjs:
    smaller: true
    scrollable: true
    slide-number: true
    chalkboard: true
    show-slide-number: all
    theme: simple
include-in-header: 
  text: |
    <style>
      .custom-small table {
        font-size: .8em
      }
    </style>
editor: visual
---

## **Credits**

-   Yashna for co-working on many aspects
-   CECAD core facility for sharing their materials
-   Julian for providing reasons not to use R
-   Copilot for helping with the exercises

## Code of Conduct

-   Treat everyone with dignity

-   Respect different learning pace

-   Share your code

-   Credit authors of the code you use

-   There are no stupid questions!

-   Use AI but check their answers 🤖

-   Help each other 😇

## Why R (and why not)?

😊

-   Good packages for statistical analysis

-   Advanced and interactive graphics

-   Open source and free

-   Biology-oriented packages in Bioconductor

😰

-   Conflicts between versions

-   Relatively slow

-   Relatively memory-hungry

## Getting help

**From us**

-   slack channel [#learning-r-beginners-2025](https://crc1678-inf.slack.com/archives/C090Z8C91M2)

-   [crc1678-inf\@uni-koeln.de](mailto:crc1678-inf@uni-koeln.de)

-   [open an issue](https://github.com/CRC-1678/Teaching-R-basics/issues/new/choose) in course GitHub repository

-   [book a Zoom consultation](https://doodle.com/bp/crc1678/crc1678inf-introductory-meeting)

**In general**

-   Use `?` or `help()` inside R

-   ask on R-specific resources: [R-bloggers](https://www.r-bloggers.com/), [Posit community](https://forum.posit.co/)

## Set up

You should have already:

-   R+RStudio installed
-   necessary packages installed: `tidyverse`

**RStudio projects**

Projects in RStudio are helpful to make your work more shareable and reproducible.

-   Code and data are organized in a directory - you can use relative file paths

-   You can store and share project-specific settings in `.Rproj` file

-   You can use version control (Git) to track changes

``` r
# does not work on your collaborator's unix-based system
data_file <- "C:/Users/svetlana/Documents/R/learning-r-beginners-2025/data/data.csv"
# use relative path (or a package "here") - works on all systems
data_file <- "data/data.csv"
```

## Live coding

-   Open RStudio
-   If you haven't, open `Exercise-R-basics.Rmd` - we will go through it together
-   If you already did: open `Exercise-R-errors.Rmd` and work on it on your own

## R startup

You can change the behavior or R/Rstudio at startup by modifying several files. The full overview can be found at [Posit](https://docs.posit.co/ide/user/ide/guide/environments/r/managing-r.html).

Most useful are `.Rprofile` and `.Renviron` which are executed at the start of R session.

-   `.Renviron` is used to set environment variables. This is useful for providing credentials such as API keys. This is not R code but a simple text file with `KEY=VALUE` pairs, one per line. For example, you can set your GitHub token like this:

``` bash
GITHUB_PAT=your_github_token_here
```

-   `.Rprofile` is used to set options and this is R code. You can use it to set options, load packages which you always use or provide custom functions. For example, you can change your default prompt to always be sure when you are in R console:

``` r
options(prompt = "R> ")
```

## R environment setup {.custom-small}

There are many possibilities to set up your development environment with R.

| Setup | Pros | Cons |
|----|----|----|
| local installation (what we did) | stable, fast, offline | "user" vs "system" package (Linux), limited resources |
| get R in an isolated `conda` environment | simple set up | not all R packages available |
| your institution's rserver on HPC | large resources | no control over set-up / update |
| container ([rocker](https://rocker-project.org/images/) images) | full control, reproducible, portable | needs admin rights, rebuild to update |
| cloud ([Posit cloud](https://posit.cloud/) / [Google Colab](https://colab.research.google.com/)) | simple and fast setup | pay for resources, online, not confidential |

## Resources

A subjective selection of books and resources to keep learning:

-   [CECAD bioinformatics core facility basic R course](https://github.com/CECADBioinformaticsCoreFacility/Basic_R_course_CGA?tab=readme-ov-file)
-   Hadley Wickham's [R for data science](https://r4ds.hadley.nz/) - basic knowledge about base R and tidyverse
-   Patrick Burns' [R inferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf) - "If you are using R and you think you’re in hell, this is a map for you"
-   A list of books from [Bioconductor](https://www.bioconductor.org/help/bioconductor-books/) - includes orchestrated analysis of data (e.g. HiC, single cell, mass spectrometry)
-   [Computational genomics with R](https://compgenomr.github.io/book/)(2020) - basics to classical machine learning, focus on genomics data
-   [Efficient R programming](https://csgillespie.github.io/efficientR/) - increase computational and programming efficiency in R
